### ISSUE TITLE
OBS Flatpak runtime deprecated.

### ISSUE THREAD

**Issue by develroo** [obsproject/obs-studio#11995]
### Operating System Info

Other

### Other OS

Debian Testing

### OBS Studio Version

31.0.2

### OBS Studio Log URL

http://nolog.neeeded.thanks

### Expected Behavior

Flatka should not need to issue a warning

### Current Behavior

Flatpak issues a warning. 
```
Info: runtime org.freedesktop.Platform.GL.default branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   com.obsproject.Studio
```

Flatpak manifest needs updating and testing. 

### Steps to Reproduce

1. flatpak update
2.
3.
...

**Comment by gxalpha** [comment]
> http://nolog.neeeded.thanks/

https://issue.closed/

Issues without logs aren't actionable. The field is required for a reason.

**Comment by develroo** [comment]
> > http://nolog.neeeded.thanks/
> 
> [https://issue.closed/](https://github.com/obsproject/.github/blob/4f26d177a6b7ed2174a5acff1dcc5443dfc67205/.github/ISSUE_TEMPLATE/bug_report.yaml?plain=1#L56)
> 
> Issues without logs aren't actionable. The field is required for a reason.

It is not with the application, it is with the build system. As you don't have any other way of reporting that other than as a bug, it has to be submitted this way.

**Comment by tytan652** [comment]
> org.freedesktop.Platform.GL.default branch 21.08 is end-of-life

We don't use 21.08 branches since a while, this is not an OBS Studio issue.

**Comment by develroo** [comment]
> > org.freedesktop.Platform.GL.default branch 21.08 is end-of-life
> 
> We don't use 21.08 branches since a while, this is not an OBS Studio issue.

OBS officially builds the flatpak so yes it IS an OBS issue. Ask whoever is in charge of packaging to look at this issue.

**Comment by derrod** [comment]
> > > org.freedesktop.Platform.GL.default branch 21.08 is end-of-life
> > 
> > 
> > We don't use 21.08 branches since a while, this is not an OBS Studio issue.
> 
> OBS officially builds the flatpak so yes it IS an OBS issue. Ask whoever is in charge of packaging to look at this issue.

The person in charge of packaging the flatpak is the one you're responding to and they're right, we have not used a runtime that is based on Freedesktop SDK 21.08 since 29.0 (released May 2023). So no idea why you are getting that warning, probably not using a first party package or something.

**Comment by develroo** [comment]
> > > > org.freedesktop.Platform.GL.default branch 21.08 is end-of-life
> > > 
> > > 
> > > We don't use 21.08 branches since a while, this is not an OBS Studio issue.
> > 
> > 
> > OBS officially builds the flatpak so yes it IS an OBS issue. Ask whoever is in charge of packaging to look at this issue.
> 
> The person in charge of packaging the flatpak is the one you're responding to and they're right, we have not used a runtime that is based on Freedesktop SDK 21.08 since 29.0 (released May 2023). So no idea why you are getting that warning, probably not using a first party package or something.

My bad. I just was looking into the build version and for some reason I seem to have 2 branches? One master and one stable. 

```
flatpak info com.obsproject.Studio/x86_64/master

OBS Studio - Live streaming and video recording software

          ID: com.obsproject.Studio
         Ref: app/com.obsproject.Studio/x86_64/master
        Arch: x86_64
      Branch: master
     License: GPL-2.0
      Origin: studio-origin
  Collection: 
Installation: system
   Installed: 479.1 MB
     Runtime: org.kde.Platform/x86_64/5.15-21.08
         Sdk: org.kde.Sdk/x86_64/5.15-21.08

      Commit: d0725be424c595df6e0bc9210bc49ebcc3f506a1518c91bc9ee5904c291735c0
     Subject: Export com.obsproject.Studio
        Date: 2021-11-28 23:05:24 +0000

```
```
flatpak info com.obsproject.Studio/x86_64/stable

OBS Studio - Live stream and record videos

          ID: com.obsproject.Studio
         Ref: app/com.obsproject.Studio/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 31.0.3
     License: GPL-2.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 540.0 MB
     Runtime: org.kde.Platform/x86_64/6.6
         Sdk: org.kde.Sdk/x86_64/6.6

      Commit: dee53614e7db9461d9e8247db81dfdfda4cdbbdad2d329a522c3946c19cc0386
      Parent: bda2690638a8f078c50a9f525e5b8a996c9186e71af1d65ff33fa7396c8de5c3
     Subject: Export com.obsproject.Studio
        Date: 2025-03-28 22:00:55 +0000
```



I have no idea how that happened other than I was an early adopter of the flatpak?  I will remove it, and it will remove the warning I suspect. 

Apologies for the confusion. And thank you for your patience.
